### ISSUE TITLE
Make file diff stat text unselectable

### ISSUE THREAD

**Issue by ChristianOellers** [hans-sperling/enhanced-github-features#21]
As addition for the text trimmer to improve filename Copy & Paste; it would be nice if the "diff stats" text could be made unselectable. This will allow double-clicking next to the filename (e.g. in the grey background right to it) for a faster Copy & Paste process than manual text selection.

---

Here is a little CSS snippet to prevent the text + icon from being selectable.
Note that the tooltip for the diff stats still works.

```css
.diff-view .file-info .diffstat.tooltipped {
    user-select: none;
    -moz-user-select: none;
}
```

<br>

### Example

![example](https://cloud.githubusercontent.com/assets/2101569/21308593/ec75d8aa-c5da-11e6-957c-f2784911a141.png)
